
Vagrant.configure(2) do |config|

	config.vm.box = "jhcook/macos-sierra"

	# config.vm.define "macos", autostart: true do |macos|
		
		# macos.vm.box = 'jhcook/macos-sierra'

		# macos.vm.network :forwarded_port, guest: 80, host: 8082, auto_correct: true
		# macos.vm.network :private_network, ip: '192.168.56.112', name: "VirtualBox Host-Only Ethernet Adapter"
		# macos.vm.synced_folder 'D:/dev/macos', '/vagrant', type: "nfs" 


	# end
	
	# config.vm.provider :virtualbox do |macos, override|

		# macos.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		# macos.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

	# end

end
