
Vagrant.configure(2) do |config|

	config.vm.define "centos7-php7", autostart: true do |centos7php7|
		
		centos7php7.vm.box = 'centos7-php7'
		centos7php7.vm.box_url = 'http://admin.oderco.com.br/downloads/vagrantbox/centos7php7.box'
		

		centos7php7.vm.network :forwarded_port, guest: 80, host: 8082, auto_correct: true
		centos7php7.vm.network :private_network, ip: '192.168.56.110'
		
		centos7php7.vm.synced_folder 'D:/dev/centos7-php7', '/var/www/html', :owner=> 'apache', :group=>'apache', :mount_options => ['dmode=777', 'fmode=777'] 

		centos7php7.vm.provision :shell, :path => 'config/centos7php7.sh'
		centos7php7.vm.provision :shell, inline: "service httpd restart", run: "always"

	end
	
	config.vm.provider :virtualbox do |centos7php7, override|

		centos7php7.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
		centos7php7.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

	end
	
	config.vm.provider "virtualbox" do |centos7php7|

     # Customize the amount of memory on the VM:
     centos7php7.memory = "2048"
   end

end
